In [2]:
import pandas as pd
import numpy as np

In [5]:
file_path = "../magic-zoomcamp/data/raw/green_tripdata_2020-10.csv.gz"
df = pd.read_csv(file_path, compression='gzip', sep=',')

/tmp/ipykernel_144585/2362885471.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, compression='gzip', sep=',')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95120 entries, 0 to 95119
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               52610 non-null  float64
 1   lpep_pickup_datetime   95120 non-null  object
 2   lpep_dropoff_datetime  95120 non-null  object
 3   store_and_fwd_flag     52610 non-null  object
 4   RatecodeID             52610 non-null  float64
 5   PULocationID           95120 non-null  int64
 6   DOLocationID           95120 non-null  int64
 7   passenger_count        52610 non-null  float64
 8   trip_distance          95120 non-null  float64
 9   fare_amount            95120 non-null  float64
 10  extra                  95120 non-null  float64
 11  mta_tax                95120 non-null  float64
 12  tip_amount             95120 non-null  float64
 13  tolls_amount           95120 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  95120 non-null  float64
 16  total_amount           95120 non-null  float64
 17  payment_type           52610 non-null  float64
 18  trip_type              52610 non-null  float64
 19  congestion_surcharge   52610 non-null  float64
dtypes: float64(15), int64(2), object(3)
memory usage: 14.5+ MB

In [7]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2020-10-01 00:31:19,2020-10-01 00:34:55,N,1.0,7,7,1.0,0.79,5.0,0.5,0.5,1.58,0.0,NaN,0.3,7.88,1.0,1.0,0.0
1,2.0,2020-10-01 00:42:12,2020-10-01 00:43:51,N,1.0,179,7,1.0,0.50,4.0,0.5,0.5,0.00,0.0,NaN,0.3,5.30,2.0,1.0,0.0
2,2.0,2020-10-01 00:53:09,2020-10-01 00:55:39,N,1.0,179,223,1.0,0.60,4.0,0.5,0.5,1.06,0.0,NaN,0.3,6.36,1.0,1.0,0.0
3,1.0,2020-10-01 00:12:29,2020-10-01 00:20:08,N,1.0,134,216,2.0,4.40,13.5,0.5,0.5,0.00,0.0,NaN,0.3,14.80,2.0,1.0,0.0
4,1.0,2020-10-01 00:32:38,2020-10-01 00:43:02,N,1.0,82,7,1.0,2.90,10.5,0.5,0.5,0.00,0.0,NaN,0.3,11.80,2.0,1.0,0.0